config/routes.rb
StudyInMorocco::Application.routes.draw do
   
  root 'welcome#home'
  
  get "document_statuses/show_docstats_for_student"
  get "document_statuses/show_docStatus_for_college"
  
  get "statistics/list_stats_for_college"
  
  get "prices/list"
  get "prices/edit"
  get "students/signup"
  get "students/create"
  get "students/edit"
  get "students/update"
  get "students/change_pass"
  get "students/signin"

  get "welcome/search"
  get "welcome/index" 
  get "welcome/boot"
  get "welcome/ajax_search"
  get "welcome/advanced_search"
  get "welcome/search_by_field"

  get "admin", to: "access#admin_login"
  get "admins/settings"
  get "admins/update"

  get "access/login"
  get "access/logout"

  get "college_admins/index"
  get "colleges_admins/edit"
  get "colleges_admins/update"
  get "colleges/new_college"
  get "colleges/create"
  get "colleges/search"
  get "colleges/import_csv"
  get "college_login", to: "access#college_login"

  get "majors/create"
  get "majors/update"
  get "majors/list_majors"
  
  get "documents/list_documents"
  get "documents/create"
  get "documents/process_documents"

  get "applications/create"
  get "applications/apply"
  get "application/download"
  get "applications/download_all"
  get "applications/success"
  get "applications/list_applications_for_college"
  get "applications/list_applications_for_student"
  get "applications/acceptance_process"
  get "applications/search_students"
  get "applications/already_applied"
  get "applications/list_of_accepted"
  get "applications/list_of_rejected"
  get "applications/list_of_inProgress"
  get "applications/inform_rejected_students"
  get "applications/inform_accepted_students"
  get "applications/delete"
  get "password_reset/password_reset_sent"
  
  resources :password_resets

  

  post ':controller(/:action(/:id(.:format)))'
  get ':controller(/:action(/:id(.:format)))'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def search
    begin  
      initilize
      if(@major_college_value == "college")
        @found_colleges = College.joins(:majors).where(["(lower(name) like ? or lower(abbreviation) like ?) and (lower(city) like ?) and lower(private_public) like ?", "%#{@q}%", "%#{@q}%", "%#{@city}%", "%#{@type}%"]).order('name').uniq(:name)
      else
        @found_majors =   College.joins(:majors).where(["lower(major_name) like ?","%#{@q}%"]).order('name').uniq(:name).page(params[:page]).per_page(20)
      end
      @found_not_like_colleges = College.joins(:majors).where("lower(name) not like ?","#{@q}")
    rescue
      render :file=>"public/404.html"
    end
  end

  def home
    map("welcome/search")
    render "home"
  end

  def index
    map("welcome/search")
    render "index"
  end

  def ajax_search
    query = params[:query]
    query = query.to_s.downcase.strip
    result = Major.select("major_name").where(["lower(major_name) like ?", "%#{query}%"]).order("major_name ASC").limit(5).uniq 
    render json: result.map(&:major_name)
  end

  def ajax_search_college
    query = params[:query]
    query = query.to_s.downcase.strip
    result = College.where(["lower(name) like ?", "%#{query}%"]).order("name ASC").limit(7).uniq
    colleges = result.map(&:name)
    render json: colleges
  end

  def search_old
    begin  
      map("search")
      render "index"
    rescue
      render :file=>"public/404.html"
    end
  end

  def advanced_search
    @bac = params[:bac].downcase
    @type = params[:public_private].downcase
    @city = params[:city].downcase
    @level = params[:level].downcase
    @price_min = params[:price_min]
    @price_max = params[:price_max]
    @cour_du_soir = params[:cour_du_soir]

    if(@price_max.empty? || @price_max.nil?)
      @price_max = 1000000
    end
    @found_colleges = College.where(["LOWER(city) LIKE ? AND private_public = ? AND avec_sans_bac LIKE ?", "%#{@city}%","#{@type}", "%#{@bac}%"]).order('name').uniq(:name)
    map("search")
    render "search"
  end

  def search_by_field
   @found_fields = College.joins(:majors).where(["lower(field) = ?", "#{params[:field].downcase}"]).order('name').uniq(:name)
    map("search")
    render "search"
  end

  private
  def map(route)
      @colleges = College.where("latitude  IS NOT NULL and longitude IS NOT NULL")
      @hash = Gmaps4rails.build_markers(@colleges) do |college, marker|
        marker.lat college.latitude
        marker.lng college.longitude
        href_value = route+"?city=&type=&major_college_value=college&q="+college.name+"&commit=Search".html_safe
        info_window_string = '<a class="info_windows">' + college.name + '</a> <br>
                              <a class="btn btn-success" href="'+href_value+'">Apply</a>'
        marker.infowindow info_window_string
      end
  end

  private
  def initilize
    @q = "" 
    @major = params[:major]
    @type = params[:type]
    @q = params[:q].downcase.strip
    @city = params[:city].downcase
    @major_college_value = params[:major_college_value].downcase
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_advanced_result_row.html.erb
<div class="row spacer">
	<div class="col-lg-12">
		<h3><%= m.major_name %></h3>
		<h4 class="expand"><%= c.name%> (<%= c.abbreviation %>)<small> more</small></h4>
		<div class="collapse">
			<div class="col-lg-6">
				<h5>Type: <%= c.private_public.capitalize %></h5>
				<h5>City: <%= c.city %></h5>
				<% if m.level %>
					<h5>Level: <%= m.level %></h5>
				<% end %>
				<h5><%= "Cours de soir: "+ m.cour_du_soir if m.cour_du_soir %></h5>
				<% if c.prices.count > 0 %>
					<h5><b>price info:</b></h5>
					<% c.prices.each do |price| %>
						<h5><%= price.amount + "dhs" %>/<%= price.price_type.capitalize %></h5>
					<% end %>
				<% end %>
			</div>
			<div class="col-lg-6">
				<h5><%= link_to "More information", "#" %></h5>
				<h5><%= link_to "College Official Website", "http://#{c.college_url}"%></h5> 
				<% if m.major_url %>
				<h5><%= link_to "More information about the major", "http://#{m.major_url}"%></h5>
				<% end %>	
				<% if c.price_url %>
					<h5><%= link_to "More information about the prices", "#{c.price_url}" %></h5>		
				<% end %>
			</div>
		</div>
		<h5>
				<%= form_tag({controller: "applications", :action=>"new"} , class: "pull-left", method: "post", style: "display: inline-block; margin-right:7px") do %>
				<%= hidden_field_tag :college_id, c.id %>
				<%= hidden_field_tag :major_id, m.id %>
				<%= submit_tag "Apply", class: "btn btn-success", :data=>{disable_with: "Waiting.."} %>
			<% end %>
				<%= form_tag({controller: "applications", :action=>"subscribe"} , class: "pull-left", method: "post", style: "display: inline-block; margin-right:7px") do %>
				<%= hidden_field_tag :college_id, c.id %>
				<%= hidden_field_tag :major_id, m.id %>
			<%#= submit_tag "Interested", class: "btn btn-primary", :data=>{disable_with: "Please wait..."} %>
			<% end %>
		</h5>
	</div>
</div>


<% @advanced_result.each do |college| %>
			<% college.majors.each do |major| %>
				<% if major.level == @level %>
					<h3>level is equal</h3>
					<h4>major name; <%= major.major_name %></h4>
					<h4>level: <%= major.level %></h4>
				<% else %>
				<% end %>
			<% end %>
		<% end %>

app/views/welcome/_list_of_cities.html.erb
<%= select_tag :city, ' <option value="">Villes</option>
						<option value="Agadir">Agadir</option>
						<option value="Ait melloul">Ait melloul</option>
						<option value="Assila">Assila</option>
						<option value="Bengurir">Bengurir</option>
						<option value="Benimellal">Benimellal</option>
						<option value="Benslimane">Benslimane</option>
						<option value="Berrchid">Berrchid</option>
						<option value="Casablanca">Casablanca</option>
						<option value="Dakar">Dakar</option>
						<option value="Dakhla">Dakhla</option>
						<option value="El Jadida">El Jadida</option>
						<option value="Errachidia">Errachidia</option>
						<option value="Essaouira">Essaouira</option>
						<option value="Fquih Ben Salah">Fquih Ben Salah</option>
						<option value="Fes">Fès</option>
						<option value="Guelmim">Guelmim</option>
						<option value="Ifrane">Ifrane</option>
						<option value="Inezagane">Inezagane</option>
						<option value="Jrada">Jrada</option>
						<option value="Kenitra">Kénitra</option>
						<option value="Khouribga">Khouribga</option>
						<option value="Kser El kebir">Kser El kebir</option>
						<option value="Laayoune">Laâyoune</option>
						<option value="Larach">Larach</option>
						<option value="Marrakech">Marrakech</option>
						<option value="Meknes">Meknes</option>
						<option value="Mohammedia">Mohammedia</option>
						<option value="Oujda">Oujda</option>
						<option value="Rabat">Rabat</option>
						<option value="Safi">Safi</option>
						<option value="Sale">Salé</option>
						<option value="Settat">Settat</option>
						<option value="Sidi Slimane">Sidi Slimane</option>
						<option value="Sousse">Sousse</option>
						<option value="Tan tan">Tan tan</option>
						<option value="Tanger">Tanger</option>
						<option value="Temara">Témara</option>
						<option value="Tetouan">Tetouan</option>'.html_safe, class: "form-control"%>

app/views/welcome/_modal_for_advanced_search.html.erb
<div class="modal fade modal_for_advanced_search" tabindex="-12" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<%= form_tag({:controller=> "welcome", :action=> "advanced_search"}, method: "get") do %>
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"><b>Recherche Avancée</b></h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-lg-6">
						<label for="public_private">Public/Privée</label>
						<%= select_tag :public_private, options_for_select([["Public","public"],["Privée", "private"], ["Les Deux", ""]]),:class=>"form-control", id: "public_private"%>
					</div>
					<div class="col-lg-6">
						<label for="Level">Level</label>
						<%= select_tag :level, options_for_select([["License","license"],["Master", "master"]]),:class=>"form-control"%> <br>
					</div>
				</div>
				<script>
				$("#price-div").hide();
				$( "#public_private" ).change(function() {
					if(($(this).val() === "private")||($(this).val() === "both")){
						$("#price-div").show(1000);
						$("#price").val("");
					}
					else {
						$("#price-div").hide(1500);
					}
				});
				</script>
				<div class="row" id="price-div" style="display:none">
					<div class="col-lg-6">
						<label for="price">Prix Minimum</label>
						<%#= text_field_tag :price_min,"",:class=>"form-control", :placeholder=>"Min value (0)", :type=>"number"%>
						<%= text_field_tag :price_min,"",:class=>"form-control", :placeholder=>"Valeur min (Dhs)", type: "number", id: "price"%>
					</div>
					<div class="col-lg-6">
						<label for="price">Prix Maximum</label>
						<%#= text_field_tag :price_min,"",:class=>"form-control", :placeholder=>"Min value (0)", :type=>"number"%>
						<%= text_field_tag :price_max,"",:class=>"form-control", :placeholder=>"valeur max (Dhs)", type: "number", id: "price"%>
					</div>

				</div>
				<div class="row">
					<div class="col-lg-6">
						<label for="cour_du_soir">Cours du Soir</label>
						<%= select_tag :cour_du_soir, options_for_select([["Oui","yes"],["Non", "no"]]), :class=>"form-control"%>
					</div>
					<div class="col-lg-6">
						<label for="avec_sans_bac">Avec/Sans bac</label>
						<%= select_tag :bac, options_for_select([["Avec","avec"],["Sans", "sans"],["Les deux", ""]]), :class=>"form-control"%> <br>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-3"></div>
					<div class="col-lg-6">
						<%= render :partial=>"welcome/list_of_cities" %>
					</div>
				</div>
			</div> <!-- end of modal body -->
			<div class="modal-footer">	
				<div class="col-lg-12">
					<button class="btn btn-danger" data-dismiss="modal">Fermer</button>
					<%= submit_tag "Search", class: "btn btn-success", :data=>{disable_with: "Searching..."} %>
				</div>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/welcome/_modal_for_map.html.erb
<style>
	#times{
		 z-index:150;
    	position:absolute;  
	}
</style>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div class="modal fade modal_for_map" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">		
		<div class="modal-content">
			<button id="times" type="button" class="close pull-right" data-dismiss="modal" aria-hidden="true">&times;</button>
			<div id="map" style='width: 900px; height: 700px;'></div>
		</div>
			<div class="row">
				<div class="col-lg-5 col-lg-offset-1">
					<button type="button" class="btn btn-danger pull-right" data-dismiss="modal">Close</button>
				</div>
			</div>			
	</div>
</div>
<script>
$(".modal_for_map").on("shown.bs.modal", function () {
	google.maps.event.trigger(map, "resize");
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
		markers = handler.addMarkers(<%=raw @hash.to_json %>);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();
		handler.getMap().setZoom(6)
	});
});
</script>

app/views/welcome/_modal_for_new_application.html.erb
<div class="modal fade modal_for_new_application" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content content-to-add">
		</div>
	</div>
</div>

app/views/welcome/_modal_for_password_reset.html.erb
<div class="modal fade modal_for_password_reset" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"><b>MOT DE PASSE OUBLIÉ: Entrez Votre Adress Émail</b></h4>
			</div>		
			<%= form_tag password_resets_path, :method=>"post", remote: "true" do %>
				<div class="modal-body">
						<%= text_field_tag :email, params[:email], class: "form-control", placeholder: "email address", type: "email", required: "true"%>
				</div>
				<div class="modal-footer">
					<button class="btn btn-danger" data-dismiss="modal">close</button>
					<%= submit_tag "Send email", class: "btn btn-success", disable_with: "Sending email..." %>				
				</div>
			<% end %>
		</div>
	</div>
</div>

<script>
	$(document).ajaxComplete(function(event, xhr, settings){
		//$(".modal_for_waiting").modal('hide');
		$(".modal_for_password_reset").modal('hide');
	});
	$(".modal_for_password_reset").modal('hide');
</script>

app/views/welcome/_modal_for_search.html.erb
<style>
	.top{
		margin-top: 10px;
	}
</style>
<div class="modal fade modal_for_search" tabindex="-12" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<%= form_tag({:controller=>"welcome", :action => "search"},{:method => "get"}) do %>
		<div class="modal-dialog">
			<div class="modal-content">
				
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title"><b>Cherchez par Etablissement/Filière</b></h4>
				</div>

				<div class="modal-body">
					<div class="row">
						<div class="col-md-6">
							<%= render :partial=>"welcome/list_of_cities" %>
						</div>
						
						<div class="col-lg-6">
							<%= select_tag :type, options_for_select([["Privée/Public",""],["Privée","private"],["Public","public"]]), {class: "form-control input-md", title: "Choose type of college"} %>
						</div>
					</div>
					
					<div class="row top">
						<div class="col-lg-5 col-md-offset-3">
							<%= radio_button_tag(:major_college_value, "major") %>
							<%= label_tag(:major, "Filière") %>&nbsp &nbsp &nbsp
							<%= radio_button_tag(:major_college_value, "college", "checked") %>
							<%= label_tag(:college, "Etablissement") %>
						</div>		
					</div>
	
					<div class="row">
						<div class="col-md-12">
							<%= text_field_tag :q, nil, :class=>"form-control input-md", :placeholder => "Etablissement/Filière", :onkeyup=>"ajax_search();return false;", :id=>"search-text", type: "search"%>
						</div>
					</div>
				</div>
				<div class="modal-footer">	
					<div class="col-lg-12">
						<button class="btn btn-danger" data-dismiss="modal">close</button>
						<%= submit_tag "Search", class: "btn btn-success", :data=>{disable_with: "Searching..."} %>
					</div>
				</div>
			</div>
		</div>
	<% end %> <!-- end of form -->
</div>	

app/views/welcome/_result_row.html - final_design backup.erb
<style>
	.row-background{
		background: url("https://www.universityadmissions.se/images/search/searchresultrowfirst.png") no-repeat;
		padding-left: 50px;
		background-color: white;
		font-family: Roboto, serif;
	}
	.row-collapsed{
		background-color: black;
		display: block;
	}
	.apply{
		
	}
	.bord{
		
	}
	.spacer{
		margin-top: 0px;
	}
</style>
<div class="row spacer">
	<div class="col-lg-7 col-lg-offset-1 bord row-background">
		<h3><%= m.major_name %></h3>
		<h4 class="expand"><%= c.name%> (<%= c.abbreviation %>)<small> more</small></h4>
		<div class="collapse">
			<div class="">
				<div class="col-lg-3">
					<h5><b>Type</b>: <%= c.private_public.capitalize %></h5>
					<h5><b>City</b>: <%= c.city %></h5>
					<% if m.level %>
						<h5><b>Level</b>: <%= m.level %></h5>
					<% end %>
					<h5> <b>Cours de soir:</b> <%=m.cour_du_soir if m.cour_du_soir %></h5>
				</div>
				<% if c.prices.count > 0 %>
					<div class="col-lg-4">
					<h5><b>price info:</b></h5>
						<% c.prices.each do |price| %>
							<h5><%= price.amount + "dhs" %>/<%= price.price_type.capitalize %></h5>
						<% end %>
					</div>
				<% end %>
				<div class="col-lg-5">
					<h5><%= link_to "More information", "#" %></h5>
					<h5><%= link_to "College Official Website", "http://#{c.college_url}"%></h5> 
					<% if m.major_url %>
						<h5><%= link_to "More information about the major", "http://#{m.major_url}"%></h5>
					<% end %>	
					<% if c.price_url %>
						<h5><%= link_to "More information about the prices", "#{c.price_url}" %></h5>		
					<% end %>
				</div>
			</div> <!--end of row-collapsed-->
		</div>
		<h5>
				<%= form_tag({controller: "applications", :action=>"new"} , class: "pull-left", method: "post", style: "display: inline-block; margin-right:7px", remote: "true") do %>
				<%= hidden_field_tag :college_id, c.id %>
				<%= hidden_field_tag :major_id, m.id %>
				<%= submit_tag "Apply", class: "btn btn-success apply", disable_with: "Waiting...", onclick: "show_modal();" %>
			<% end %>
				<%= form_tag({controller: "applications", :action=>"subscribe"} , class: "pull-left", method: "post", style: "display: inline-block; margin-right:7px") do %>
				<%= hidden_field_tag :college_id, c.id %>
				<%= hidden_field_tag :major_id, m.id %>
			<%#= submit_tag "Interested", class: "btn btn-primary", :data=>{disable_with: "Please wait..."} %>
			<% end %>
		</h5>
	</div>
</div>

app/views/welcome/_result_row.html.erb
<td width="40%">
	<h4 class=""><%= m.major_name %></h4>
	<h5><%= c.name%> (<%= c.abbreviation %>)</h5>	
	<% if m.level %>
		<h6><b>Niveau</b>: <%= m.level %></h6>
	<% end %>
	<% if m.duration %>
		<h6> <b>Durée: </b> m.duration</h6>
	<% end %>
</td>

<td>
	<h6><b>Type</b>: <%= c.private_public.capitalize %></h6>
	<h6><b>Ville</b>: <%= c.city %></h6>
	<h6><b>Telephone</b>: <%= c.phone %></h6>
	<h6><b>Cours du soir:</b> <%=m.cour_du_soir if m.cour_du_soir %></h6>
</td>

<td>
	<% if c.prices.count > 0 %>
			<h6><b>Prix:</b></h6>
			<% c.prices.each do |price| %>
				<h6><%= price.amount + "dhs" %>/<%= price.price_type.capitalize %></h6>
			<% end %>
	<% else %>
		 <h6>Etablissement Public</h6>		
	<% end %>
</td>

<td>
		<h6><b>Plus d'information:</b></h6>
		<% if m.major_url %>
			<h6><%= link_to "Filière", " #{m.major_url}"%></h6>
		<% end %>	
		<% if c.price_url %>
			<h6><%= link_to "Prix", "#{c.price_url}" %></h6>		
		<% end %>
		<h6><%= link_to "Site Officiel", "http://#{c.college_url}"%></h6> 
</td>

<td>
	<h6>
		<%= form_tag({controller: "applications", :action=>"new", remote: "true"} , class: "pull-left", method: "post", style: "display: inline-block; margin-right:7px", remote: "true") do %>
			<%= hidden_field_tag :college_id, c.id %>
			<%= hidden_field_tag :major_id, m.id %>
			<%= submit_tag "Postulez", class: "btn btn-success apply", disable_with: "Waiting..."%>
		<% end %>
	</h6>
</td>

app/views/welcome/_search_result.html.erb
<style>
	table{
		color: #2c2c2c;
	}
	td:hover{
		background-color: red;
	}
</style>
<% class_name = ["info","primary"] %>
<% cnt = 0 %>
<div class="row row-result result">
	<table class="table table-hover table-striped">
		<% if @found_colleges %>
			<% if @found_colleges.empty? || @found_colleges.nil? %>
				<h2>No Result for <%= params[:q] %></h2>
			<% end %>
			<% @found_colleges.each do |c|%>
				<% c.majors.each do |m| %>
					<% cnt = 0 if cnt == 2 %>
					<tr class="<%= class_name[cnt]%>"><%= render :partial=>"result_row", :locals=>{:c=>c, :m=>m} %></tr>
					<% cnt += 1 %>
				<% end %>
			<% end %>
		<% elsif @found_majors %>
			<% if @found_majors.empty? || @found_majors.nil? %>
				<h2>No Result for <%= params[:q] %></h2>
			<% end %>
		<!-- major radio button was selected-->
			<% @found_majors.each do |c|%>
				<% c.majors.each do |m| %>
					<% if m.major_name.to_s.downcase.include? "#{@q}" %>
						<% cnt = 0 if cnt == 2 %>
						<tr class="<%= class_name[cnt]%>"><%= render :partial=>"result_row", :locals=>{:c=>c, :m=>m} %></tr>
						<% cnt += 1 %>
					<% end %>
				<% end %>
			<% end %>
		<% elsif @advanced_result%>
		<!-- for advanced seach -->
			<% if @advanced_result.empty? %>
				<h2>No Result for <%= params[:q] %></h2>
			<% end %>
			<% @advanced_result.each do |c| %>
				<% c.majors.each do |m| %>
					<% if m.level == @level && m.cour_du_soir%>
						<% c.prices.each do |p|%>
							<% if p.amount.to_f.between?(@price_min.to_f, @price_max.to_f) %>
								<% cnt = 0 if cnt == 2 %>
								<tr class="<%= class_name[cnt]%>"><%= render :partial=>"result_row", :locals=>{:c=>c, :m=>m}%></tr>
								<% cnt += 1 %>
								<% break %>
							<% end %>
						<% end %>
					<% else %>
					<% end %>
				<% end %>
			<% end %>
		<% else %>
		<!-- search by field @found_fields is not nil-->
			<% if @found_fields.nil? || @found_fields.empty? %>
				<tr class="row">
					<h2>       No result found for "<%= params[:field] %>"</h2>
				</tr>
			<% end %>
			<% @found_fields.each do |c| %>
				<% c.majors.each do |m| %>
					<% if m.field == params[:field] %>
						<tr class="<%= class_name[cnt]%>"><%= render :partial=>"result_row", :locals=>{:c=>c, :m=>m}%></tr>
					<% end %>
				<% end %>
			<% end %>
			
		<% end %>
	</table>
</div>


<%#= render :partial=> "application/modal_for_waiting" %>

<div class="modal fade modal_for_waiting" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
	
	</div>
</div>

app/views/welcome/_signupModel.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">S'enregistrer</h4>
				<h6 class="modal-title text-danger">Enter Correct Information, they will be sent to the college you are applying to</h6>
			</div>
			<div class="modal-body">
				<%= form_for :student, :url=>{:controller=>"students", :action=>"create"} do |f| %>
				<%= render :partial=>"students/fields_for_signup_student", :locals=>{:f=>f} %>
				<div class="row">	
					<div class="col-lg-offset-6">
						<button class="btn btn-danger" data-dismiss="modal">close</button>
						<%= submit_tag "Register", class: "btn btn-success", disable_with: "Registering .." %>
					</div>	
				</div>
				<% end %> <!-- end of form tag -->
			</div> <!-- end of modal body -->		
		</div>
	</div>
</div>

app/views/welcome/map.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<div style='width: 800px;'>
	<div id="map" style='width: 800px; height: 700px;'></div>
</div>

<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	markers = handler.addMarkers(<%=raw @hash.to_json %>);
	handler.bounds.extendWith(markers);
	handler.fitMapToBounds();
	handler.getMap().setZoom(6)
});
</script>

app/views/welcome/search.html.erb
<%= render :partial=>"search_result" %>